"""Agent Session Gene — syncs client-generated agent session summaries."""

from __future__ import annotations

import json
import logging
import re
from collections.abc import AsyncIterator
from datetime import datetime
from pathlib import Path

from memforge.agent_session_contract import (
    AGENT_SESSION_CONTENT_ROLE,
    AGENT_SESSION_PACKAGE_KIND,
)
from memforge.agent_sessions import normalize_repo_identifier
from memforge.genes.base import Gene
from memforge.models import (
    ConfigField,
    ConfigFieldType,
    ConfigGroup,
    ContentItem,
    GeneConfigSchema,
    GeneMetadata,
    NormalizedContent,
    RawContent,
)

__all__ = ["AgentSessionGene"]

logger = logging.getLogger(__name__)


_OPERATIONAL_SUMMARY_SECTIONS = {
    "commands",
    "evidence",
    "execution notes",
    "files",
    "local evidence",
    "open questions",
    "operational notes",
    "runtime notes",
    "test results",
    "touched files",
    "validation",
    "validation evidence",
    "verification",
    "verification notes",
}


def _parse_dt(value: str) -> datetime:
    return datetime.fromisoformat(value.replace("Z", "+00:00"))


def _heading(line: str) -> tuple[int, str] | None:
    match = re.match(r"^(#{1,6})\s+(.+?)\s*#*\s*$", line)
    if not match:
        return None
    return len(match.group(1)), match.group(2).strip()


def _section_key(title: str) -> str:
    return re.sub(r"[^a-z0-9]+", " ", title.lower()).strip()


def _memory_visible_markdown(markdown: str) -> str:
    """Return the submitted summary text that should enter memory extraction."""
    visible_lines: list[str] = []
    skip_level: int | None = None
    for line in markdown.splitlines():
        heading = _heading(line)
        if heading:
            level, title = heading
            if skip_level is not None and level <= skip_level:
                skip_level = None
            if skip_level is None and level <= 2 and _section_key(title) in _OPERATIONAL_SUMMARY_SECTIONS:
                skip_level = level
                continue
        if skip_level is None:
            visible_lines.append(line)
    return "\n".join(visible_lines).strip() + "\n"


def _looks_like_legacy_hook_capture(package: dict) -> bool:
    title = str(package.get("title") or "")
    markdown = str(package.get("markdown") or "").lstrip()
    receipt = package.get("receipt") or {}
    metadata = receipt.get("metadata") or {}
    return (
        title.startswith("Agent Session Hook Capture:")
        or markdown.startswith("# Agent Session Hook Capture")
        or "hook_event_name" in metadata
    )


def _is_ingestable_agent_session_package(package: dict) -> bool:
    package_kind = package.get("package_kind")
    content_role = package.get("content_role")
    if package_kind is not None or content_role is not None:
        return (
            package_kind == AGENT_SESSION_PACKAGE_KIND
            and content_role == AGENT_SESSION_CONTENT_ROLE
        )
    return not _looks_like_legacy_hook_capture(package)


class AgentSessionGene(Gene):
    """Generated agent session summaries.

    The source unit is a JSON package created by the agent-session intake API.
    The package contains receipt metadata plus redacted markdown generated by a
    client such as Codex or Claude Code.
    """

    @classmethod
    def metadata(cls) -> GeneMetadata:
        return GeneMetadata(
            name="agent_session",
            display_name="Agent Session",
            description="Client-generated coding-agent session summaries",
            default_sync_interval_minutes=0,
            auth_method="local_file",
            data_shape="message",
        )

    @classmethod
    def config_schema(cls) -> GeneConfigSchema:
        return GeneConfigSchema(
            groups=[ConfigGroup(key="storage", label="Storage", order=0)],
            fields=[
                ConfigField(
                    key="documents_dir",
                    label="Submitted Documents Directory",
                    field_type=ConfigFieldType.STRING,
                    required=True,
                    placeholder="~/.memforge/agent-session-submissions",
                    help_text="Local directory containing generated session summary packages",
                    group="storage",
                    order=0,
                ),
                ConfigField(
                    key="client",
                    label="Client",
                    field_type=ConfigFieldType.STRING,
                    required=False,
                    placeholder="codex",
                    help_text=(
                        "Client slug this source ingests (e.g. 'codex', 'claude-code'). "
                        "When set, the gene only picks up packages whose receipt.client "
                        "matches this value. Leave empty to ingest all clients."
                    ),
                    group="storage",
                    order=1,
                ),
            ],
            project_field="repo",
        )

    async def authenticate(self) -> None:
        documents_dir = Path(self.config["documents_dir"]).expanduser()
        if not documents_dir.exists():
            raise FileNotFoundError(f"Agent session documents directory does not exist: {documents_dir}")
        if not documents_dir.is_dir():
            raise NotADirectoryError(f"Agent session documents path is not a directory: {documents_dir}")

    async def discover(self, since: datetime | None = None) -> AsyncIterator[ContentItem]:
        documents_dir = Path(self.config["documents_dir"]).expanduser()
        configured_client = self.config.get("client")
        for package_path in sorted(documents_dir.rglob("*.json")):
            package = json.loads(package_path.read_text(encoding="utf-8"))
            if not _is_ingestable_agent_session_package(package):
                logger.warning(
                    "Skipping non-summary agent session package: %s",
                    package_path,
                )
                continue
            receipt = package.get("receipt", {})
            # Per-client sources share a documents_dir, so each gene must filter
            # the directory by receipt.client to avoid stamping foreign clients'
            # documents with its own source id. Legacy single-source mode (no
            # configured client) keeps the unfiltered behavior.
            if configured_client and receipt.get("client") != configured_client:
                continue
            last_modified = _parse_dt(package["last_modified"])
            if since and last_modified <= since:
                continue

            yield ContentItem(
                item_id=package["doc_id"],
                title=package["title"],
                source_url=package["source_url"],
                last_modified=last_modified,
                content_type="application/json",
                space_or_project=package.get("space_or_project") or receipt.get("repo") or "",
                version=package["version"],
                author=receipt.get("client"),
                labels=[
                    "generated_agent_summary",
                    f"trigger:{receipt.get('trigger', 'unknown')}",
                ],
                extra={"package_path": str(package_path)},
            )

    async def fetch(self, item: ContentItem) -> RawContent:
        package_path = Path(item.extra["package_path"])
        return RawContent(
            item=item,
            body=package_path.read_bytes(),
            content_type="application/json",
        )

    async def normalize(self, raw: RawContent) -> NormalizedContent:
        package = json.loads(raw.body.decode("utf-8"))
        receipt = package.get("receipt", {})
        receipt_metadata = receipt.get("metadata") or {}
        markdown = package.get("markdown", "")
        # The uploader hint is a write-time signal that travels with the package
        # so the sync pipeline can stamp the correct owner at persistence time.
        # It is never authoritative for retrieval; the access predicate stays in
        # charge of read-time visibility.
        uploader_user_id = receipt_metadata.get("user_id")

        return NormalizedContent(
            item=raw.item,
            markdown_body=_memory_visible_markdown(markdown),
            source_semantics={
                "source_kind": receipt.get("source_kind", "generated_agent_summary"),
                "client": receipt.get("client"),
                "session_id": receipt.get("session_id"),
                "trigger": receipt.get("trigger"),
                "workspace": receipt.get("workspace"),
                "repo": receipt.get("repo"),
                "repo_identifier": (
                    receipt_metadata.get("repo_identifier")
                    or normalize_repo_identifier(receipt.get("repo"))
                ),
                "branch": receipt.get("branch"),
                "commit_sha": receipt.get("commit_sha"),
                "history_window_kind": receipt.get("history_window_kind"),
                "uploader_user_id": uploader_user_id,
                "source_updated_at": package.get("source_updated_at"),
            },
        )

    async def health_check(self) -> dict:
        documents_dir = Path(self.config.get("documents_dir", "")).expanduser()
        return {
            "healthy": documents_dir.exists() and documents_dir.is_dir(),
            "documents_dir": str(documents_dir),
        }
